services:
  mysql:
    image: mysql:8.0
    container_name: peersphere-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Ciphersoul@45
      MYSQL_DATABASE: peersphere
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 20s
